seismology/web/main/routes/main.py
import json

import requests
from flask import Blueprint, current_app, flash, make_response, redirect, url_for
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_user, logout_user

from ..forms.login_form import LoginForm
from . import verified_seism
from .auth import User

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/")
@register_breadcrumb(main, "breadcrumbs.", "Home")
def index():
    return redirect(url_for("verified_seism.index"))


@main.route("/login", methods=["POST"])
def login():
    loginForm = LoginForm()
    if loginForm.validate_on_submit():
        # Enviar requests
        data = (
            '{"email":"'
            + loginForm.email.data
            + '", "password":"'
            + loginForm.password.data
            + '"}'
        )
        r = requests.post(
            current_app.config["API_URL"] + "/auth/login",
            headers={"content-type": "application/json"},
            data=data,
        )
        # Si la request se realiza con exito
        if r.status_code == 200:
            # Cargar valores del usuario de la respuesta
            user_data = json.loads(r.text)
            user = User(
                id=user_data.get("id"),
                email=user_data.get("email"),
                admin=user_data.get("admin"),
            )
            # Loguear objeto usuario
            login_user(user)
            # Crear una request de redireccion
            req = make_response(redirect(url_for("main.index")))
            # Setear cookie con el valor del token
            req.set_cookie("access_token", user_data.get("access_token"), httponly=True)
            # Realizar la request
            return req
        else:
            # Mostrar error de autenticacion
            flash("Usuario o contraseña incorrecta", "danger")
    return redirect(url_for("main.index"))


@main.route("/logout")
def logout():
    # Crear una request de redireccion
    req = make_response(redirect(url_for("main.index")))
    # Vaciar cookie
    req.set_cookie("access_token", "", httponly=True)
    # Desloguear usuario
    logout_user()
    # Realizar request
    return req

seismology/web/main/routes/sensor.py
import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required

from ..forms.sensor_form import SensorCreateForm, SensorEditForm, SensorFilterForm
from ..utilities.functions import sendRequest
from .auth import admin_required

sensor = Blueprint("sensor", __name__, url_prefix="/sensor")


@sensor.route("/")
@login_required
@admin_required
@register_breadcrumb(sensor, ".", "Sensors")
def index():
    # Eliminar la protección csrf para el formulario de filtro
    # Cargar parametros de la url en el formulario
    filter = SensorFilterForm(request.args, meta={"csrf": False})
    # Obtener usuarios
    r = sendRequest(method="get", url="/users-info")

    # Cargar usuarios en el formulario
    filter.userId.choices = [
        (int(user["id"]), user["email"]) for user in json.loads(r.text)["Users"]
    ]
    filter.userId.choices.insert(0, [0, "All"])
    data = {}
    # Aplicado de filtros
    # Validar formulario de filtro
    if filter.validate():
        if filter.userId.data != None and filter.userId.data != 0:
            data["userId"] = filter.userId.data
        if filter.name.data != None:
            data["name"] = filter.name.data
        if filter.status.data:
            data["status"] = filter.status.data
        if filter.active.data:
            data["active"] = filter.active.data

    # Ordenamiento
    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    # Obtener datos de la api
    r = sendRequest(method="get", url="/sensors", data=json.dumps(data), auth=True)

    if r.status_code == 200:
        sensors = json.loads(r.text)["sensors"]
        pagination = {}
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]
        title = "Sensors"
        return render_template(
            "sensors.html",
            title=title,
            sensors=sensors,
            filter=filter,
            pagination=pagination,
        )
    else:
        flash("Error de filtrado", "danger")
        return redirect(url_for("sensor.index"))


@sensor.route("/view/<int:id>")
@login_required
@admin_required
@register_breadcrumb(sensor, ".view", "Sensor")
def view(id):
    r = sendRequest(method="get", url="/sensor/" + str(id), auth=True)
    if r.status_code == 404:
        flash("Sensor not found", "danger")
        return redirect(url_for("sensor.index"))
    sensor = json.loads(r.text)
    title = "Sensor View"
    return render_template("sensor_view.html", title=title, sensor=sensor)


@sensor.route("/create", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(sensor, ".create", "Create Sensor")
def create():
    form = SensorCreateForm()  # Instanciar formulario
    if (
        form.validate_on_submit()
    ):  # Si el formulario ha sido enviado y es valido correctamente
        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "userId": form.userId.data,
        }
        data = json.dumps(sensor)
        r = sendRequest(method="post", url="/sensors", data=data, auth=True)
        return redirect(url_for("sensor.index"))  # Redirecciona a la lista
    return render_template("sensor_edit.html", form=form)


@sensor.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(sensor, ".edit", "Edit Sensor")
def edit(id):
    form = SensorEditForm()
    req = sendRequest(method="get", url="/users-info")
    users = [(int(user["id"]), user["email"]) for user in json.loads(req.text)["Users"]]
    form.userId.choices = users
    form.userId.choices.insert(0, [0, "Select one user"])
    if not form.is_submitted():
        r = sendRequest(method="get", url="/sensor/" + str(id), auth=True)
        if r.status_code == 404:
            flash("Sensor not found", "danger")
            return redirect(url_for("sensor.index"))
        sensor = json.loads(r.text)

        # Load data
        form.name.data = sensor["name"]
        form.ip.data = sensor["ip"]
        form.port.data = sensor["port"]
        form.status.data = sensor["status"]
        form.active.data = sensor["active"]

        # Load users
        try:
            for user_id, user_email in users:
                if sensor["user"]["id"] == user_id:
                    form.userId.data = user_id
        except KeyError:
            pass

    if form.validate_on_submit():
        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "userId": form.userId.data,
        }
        data = json.dumps(sensor)
        r = sendRequest(method="put", url="/sensor/" + str(id), data=data, auth=True)
        flash("Sensor edited", "success")
        return redirect(url_for("sensor.index"))

    return render_template("sensor_edit.html", id=id, form=form)


@sensor.route("/delete/<int:id>")
@login_required
@admin_required
def delete(id):
    r = sendRequest(method="delete", url="/sensor/" + str(id), auth=True)
    flash("Sensor deleted", "danger")
    return redirect(url_for("sensor.index"))

seismology/web/main/routes/unverified_seism.py
import json

from flask import Blueprint, flash, redirect, render_template, url_for, request, flash
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required

from .auth import admin_required
from ..forms.seism_form import UnverifiedSeismEditForm, SeismFilterForm
from ..utilities.functions import sendRequest

unverified_seism = Blueprint(
    "unverified_seism", __name__, url_prefix="/unverified-seism"
)


@unverified_seism.route("/")
@login_required
@register_breadcrumb(unverified_seism, ".", "Unverified Seisms")
def index():
    filter = SeismFilterForm(request.args, meta={"csrf": False})

    r = sendRequest(method="get", url="/sensors-info")
    filter.sensorId.choices = [
        (int(sensor["id"]), sensor["name"]) for sensor in json.loads(r.text)["sensors"]
    ]
    filter.sensorId.choices.insert(0, [0, "All"])
    data = {}
    # Aplicado de filtros
    # Validar formulario de filtro
    if filter.validate():
        # Datetime
        if filter.from_datetime.data and filter.to_datetime.data:
            if filter.from_datetime.data == filter.to_datetime.data:
                data["datetime"] = filter.to_datetime.data.strftime("%Y-%m-%d %H:%M")
        if filter.from_datetime.data != None:
            data["from_datetime"] = filter.from_datetime.data.strftime("%Y-%m-%d %H:%M")
        if filter.to_datetime.data != None:
            data["to_datetime"] = filter.to_datetime.data.strftime("%Y-%m-%d %H:%M")

        # SensorId
        if filter.sensorId.data != None and filter.sensorId.data != 0:
            data["sensorId"] = filter.sensorId.data

        # Depth
        if filter.depth_min.data != None:
            data["depth_min"] = filter.depth_min.data
        if filter.depth_max.data != None:
            data["depth_max"] = filter.depth_max.data

        # Magnitude
        if filter.magnitude_min.data != None:
            data["magnitude_min"] = filter.magnitude_min.data
        if filter.magnitude_max.data != None:
            data["magnitude_max"] = filter.magnitude_max.data

    # Ordenamiento
    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    # Obtener datos de la api para la tabla
    r = sendRequest(
        method="get", url="/unverified-seisms", data=json.dumps(data), auth=True
    )

    if r.status_code == 200:
        unverified_seisms = json.loads(r.text)["Unverified-seisms"]
        # Cargar datos de paginacion
        pagination = {}
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]
        title = "Unverified Seisms List"
        return render_template(
            "unverified_seisms.html",
            title=title,
            unverified_seisms=unverified_seisms,
            filter=filter,
            pagination=pagination,
        )
    else:
        flash("Error de filtrado", "danger")
        return redirect(url_for("unverified_seism.index"))


@unverified_seism.route("/view/<int:id>")
@login_required
@register_breadcrumb(unverified_seism, ".view", "Unverified Seism")
def view(id):
    r = sendRequest(method="get", url="/unverified-seism/" + str(id), auth=True)
    if r.status_code == 404:
        flash("Seism not found", "danger")
        return redirect(url_for("unverified_seism.index"))
    unverified_seism = json.loads(r.text)
    title = "Unverified Seism View"
    return render_template(
        "unverified_seism_view.html", title=title, unverified_seism=unverified_seism
    )


@unverified_seism.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@register_breadcrumb(unverified_seism, ".edit", "Edit Unverified Seism")
def edit(id):
    form = UnverifiedSeismEditForm()
    if not form.is_submitted():
        r = sendRequest(method="get", url="/unverified-seism/" + str(id), auth=True)
        if r.status_code == 404:
            flash("Unvrified Seism not found", "danger")
            return redirect(url_for("unverified_seism.index"))
        unverified_seism = json.loads(r.text)
        form.depth.data = unverified_seism["depth"]
        form.magnitude.data = unverified_seism["magnitude"]
        form.verified.data = unverified_seism["verified"]

    if form.validate_on_submit():
        unverified_seism = {
            "depth": form.depth.data,
            "magnitude": form.magnitude.data,
            "verified": form.verified.data,
        }
        data = json.dumps(unverified_seism)
        r = sendRequest(
            method="put", url="/unverified-seism/" + str(id), data=data, auth=True
        )
        flash("Unverified Seism edited", "success")
        return redirect(url_for("unverified_seism.index"))
    return render_template("unverified_seism_edit.html", form=form, id=id)


@unverified_seism.route("/delete/<int:id>")
@login_required
def delete(id):
    r = sendRequest(method="delete", url="/unverified-seism/" + str(id), auth=True)
    flash("Unverified Seism deleted", "danger")
    return redirect(url_for("unverified_seism.index"))


@unverified_seism.route("/create", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(unverified_seism, ".create", "Create Sensor")
def create():
    r = sendRequest(method="post", url="/unverified-seisms", auth=True)
    flash("Unverified Seism created", "success")
    return redirect(url_for("unverified_seism.index"))  # Redirecciona a la lista

seismology/web/main/routes/user.py
import json

from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required

from ..forms.user_form import UserCreateForm, UserEditForm
from ..utilities.functions import sendRequest
from .auth import admin_required

user = Blueprint("user", __name__, url_prefix="/user")


@user.route("/")
@login_required
@admin_required
@register_breadcrumb(user, ".", "Users")
def index():
    data = {}
    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    # Obtener datos de la api
    r = sendRequest(method="get", url="/users", data=json.dumps(data), auth=True)

    if r.status_code == 200:
        users = json.loads(r.text)["Users"]
        pagination = {}
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]
        title = "Users List"
        # Mostrar template
        return render_template(
            "users.html",
            title=title,
            users=users,
            pagination=pagination,
        )
    else:
        return redirect(url_for("user.index"))


@user.route("/view/<int:id>")
@login_required
@admin_required
@register_breadcrumb(user, ".view", "View")
def view(id):
    r = sendRequest(method="get", url="/user/" + str(id), auth=True)
    if r.status_code == 404:
        flash("User not found", "danger")
        return redirect(url_for("user.index"))
    user = json.loads(r.text)
    title = "User View"
    return render_template("user_view.html", title=title, user=user)


@user.route("/create", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(user, ".create", "Create User")
def create():
    form = UserCreateForm()  # Instanciar formulario
    if (
        form.validate_on_submit()
    ):  # Si el formulario ha sido enviado y es valido correctamente
        user = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data,
        }
        data = json.dumps(user)
        r = sendRequest(method="post", url="/users", data=data, auth=True)
        return redirect(url_for("user.index"))  # Redirecciona a la lista
    # Muestra el formulario
    return render_template("user_create.html", form=form)


@user.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(user, ".edit", "Edit User")
def edit(id):
    form = UserEditForm()
    if not form.is_submitted():
        r = sendRequest(method="get", url="/user/" + str(id), auth=True)
        if r.status_code == 404:
            flash("User not found", "danger")
            return redirect(url_for("user.index"))
        user = json.loads(r.text)
        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        user = {"email": form.email.data, "admin": form.admin.data}
        data = json.dumps(user)
        r = sendRequest(method="put", url="/user/" + str(id), data=data, auth=True)
        flash("User edited", "success")
        return redirect(url_for("user.index"))
    return render_template("user_edit.html", form=form, id=id)


@user.route("/delete/<int:id>")
@login_required
@admin_required
def delete(id):
    r = sendRequest(method="delete", url="/user/" + str(id), auth=True)
    flash("User deleted", "danger")
    return redirect(url_for("user.index"))

seismology/web/main/templates/macros.html
{% macro show_verified_seism(verified_seism) %}
<tr>
  <th scope="row">{{verified_seism.id}}</th>
  <td>{{verified_seism.datetime}}</td>
  <td>{{verified_seism.depth}}</td>
  <td>{{verified_seism.magnitude}}</td>
  <td>{{verified_seism.sensor.name}}</td>
  <td>
    <div class="btn-group" role="group">

      <a class="btn btn-sm btn-dark" type="button" href="{{ url_for('verified_seism.view', id=verified_seism.id) }}">
        <i class="fas fa-eye"></i></a>

    </div>
  </td>
</tr>
{% endmacro %}

{% macro show_unverified_seism(unverified_seism) %}
<tr>
  <th scope="row">{{unverified_seism.id}}</th>
  <td>{{unverified_seism.datetime}}</td>
  <td>{{unverified_seism.depth}}</td>
  <td>{{unverified_seism.magnitude}}</td>
  <td>{{unverified_seism.sensor.name}}</td>
  <td>
    <div class="btn-group" role="group">

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('unverified_seism.view', id=unverified_seism.id)}}">
        <i class="fas fa-eye"></i></a>

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('unverified_seism.edit', id=unverified_seism.id)}}">
        <i class="fas fa-edit"></i></a>

      <a class="btn btn-sm btn-dark" type="button"
        href="{{url_for('unverified_seism.delete', id=unverified_seism.id)}}">
        <i class="fas fa-trash"></i></a>

    </div>
  </td>
</tr>
{% endmacro %}

{% macro show_user(user) %}
<tr>
  <th scope="row">{{user.id}}</th>
  <td>{{user.email}}</td>
  <td>{{user.admin}}</td>
  <td>
    <div class="btn-group" role="group">

      <a class="btn btn-sm btn-dark" type="button" href="{{ url_for('user.view',id=user.id) }}">
        <i class="fas fa-eye"></i></a>

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('user.edit', id=user.id)}}">
        <i class="fas fa-edit"></i></a>

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('user.delete',id=user.id)}}">
        <i class="fas fa-trash"></i></a>

    </div>
  </td>
</tr>
{% endmacro %}

{% macro show_sensor(sensor) %}
<tr>
  <th scope="row">{{sensor.id}}</th>
  <td>{{sensor.name}}</td>
  <td>{{sensor.status}}</td>
  <td>{{sensor.active}}</td>
  <td>
    {% if sensor.user %}
    {{sensor.user.email}}
    {% endif %}
  </td>
  <td>
    <div class="btn-group" role="group">

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.view',id=sensor.id)}}">
        <i class="fas fa-eye"></i></a>

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.edit', id=sensor.id)}}">
        <i class="fas fa-edit"></i></a>

      <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.delete',id=sensor.id)}}">
        <i class="fas fa-trash"></i></a>
    </div>
  </td>
</tr>
{% endmacro %}

seismology/web/main/templates/main.html
<!-- Importar macros de formulario -->
{% from "form_macros.html" import show_field, show_submit, show_placeholder %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>

  {% block head %}

  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <!-- Style CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

  {% endblock %}

</head>

<body>

  {% block scripts %}
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  {% endblock %}

  {% block menu %}
  <header>
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <!-- Logo -->
        <a class="navbar-brand logo font-weight-bold" href="{{url_for('main.index')}}">
          <i class="fas fa-database"></i> Seismology </a>

        <!-- Collapse Button -->
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Items del Navbar -->
        <div id="navcol-1" class="collapse navbar-collapse">
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item" role="presentation">
              <a class="nav-link" href="{{url_for('verified_seism.index')}}">Verified Seisms</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item" role="presentation">
              <a class="nav-link" href="{{url_for('unverified_seism.index')}}">Unverified Seisms</a>
            </li>
            {% if current_user.admin %}
            <li class="nav-item" role="presentation">
              <a class="nav-link" href="{{url_for('sensor.index')}}">Sensors</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link" href="{{url_for('user.index')}}">Users</a>
            </li>
            {% endif %}
            {% endif %}
          </ul>
          {% if current_user.is_authenticated %}
          <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item dropdown" role="presentation">
              <a class="nav-link dropdown-toggle" id="profile" data-toggle="dropdown">
                {{ current_user.email }}
              </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="profile">
                <a class="dropdown-item" href="{{ url_for('main.logout') }}">Log out</a>
              </div>
            </li>

          </ul>
          {% else %}

          <form class="form-inline" method="POST" action="{{ url_for('main.login') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-row">
              <div class="form-group col-md-5">
                {{ show_placeholder(loginForm.email, class="form-control mr-sm-2") }}
              </div>
              <div class="form-group col-md-5">
                {{ show_placeholder(loginForm.password, class="form-control") }}
              </div>
              <div class="form-group col-md-2">
                {{ show_submit(loginForm.submit, class="btn btn-success") }}
              </div>
            </div>
          </form>
          {% endif %}


        </div>

      </div>
    </nav>
  </header>
  {% endblock %}

  {% block breadcrumbs %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      {% for breadcrumb in breadcrumbs %}
      <li class="breadcrumb-item">
        {% if not loop.last %}
        <a class="text-light" href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
        {% else %}
        {{ breadcrumb.text }}
        {{ "/" if not loop.last }}
        {% endif %}
      </li>
      {% endfor %}
    </ol>
  </nav>
  {% endblock %}

  {% block flash %}
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <span>{{ message }}</span>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>
  {% endblock %}

  <br>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <br><br>

  {% block footer %}
  <footer class="footer mt-auto py-3">
    <div class="container justify-content-center">
      <div class="row">
        <div class="col-auto">
          <small class="text-center text-light">Copyright © Seismology 2020</small>
        </div>
      </div>
    </div>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container justify-content-center pt-3">
        <div class="row">
          <p>Copyright © Seismology 2020</p>
        </div>
      </div>
      </div>
    </nav> -->
  </footer>
  {% endblock %}

</body>

</html>

seismology/web/main/templates/sensor_edit.html
<!-- Hereda del template main -->
{% extends "main.html" %} {# Herencia #}

<!-- Importar el archivo de macros -->
{% import "macros.html" as macro %}

<!-- Importar macros de formulario -->
{% from "form_macros.html" import show_field, show_submit %}

<!-- Define el contenido -->
{% block content %}
<!-- Contenido -->
<div class="container">
    <div class="row">
        <div class="col-md-2 d-none d-md-block"></div>
        <div class="col-md-8">
            <h1>Edit Sensor</h1>
            <form method="POST" action="{{ url_for('sensor.edit', id=id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

                <div class="form-group">
                    <div class="col-auto">
                        {{ show_field(form.name, class="form-control") }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-auto">
                        {{ show_field(form.ip, class="form-control") }} <br>
                        {{ show_field(form.port, class="form-control") }} <br>
                        {{ show_field(form.status, type="checkbox") }} <br>
                        {{ show_field(form.active, type="checkbox") }} <br>
                        {{ show_field(form.userId, class="form-control") }} <br>
                    </div>

                    <div class="col-auto">
                        <!-- Llama a macro especial para mostrar el campo de submit -->
                        {{ show_submit(form.submit, class="btn btn-success") }}
                    </div>
            </form>
        </div>
        <div class="col-md-2 d-none d-md-block"></div>
    </div>
</div>
{% endblock %}

seismology/web/main/templates/user_view.html
<!-- Hereda del template main -->
{% extends "main.html" %}

<!-- Importar el archivo de macros -->
{% import "macros.html" as macro %}

<!-- Define el contenido -->
{% block content %}
<!-- Contenido -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 d-none d-md-block"></div>
        <div class="col-md-4">
            <h1>Detailed User</h1>

            <div class="table-responsive text-center">
                <table class="table table-dark table-striped table-hover table-bordered">
                    <caption>
                        <a name="modify" class="btn btn-success" href="{{url_for('user.edit',id=user.id)}}"
                            role="button">Modify</a>
                        <a name="delete" class="btn btn-danger" href="{{url_for('user.delete',id=user.id)}}"
                            role="button">Delete</a>
                    </caption>
                    <tbody>
                        <tr>
                            <th scope="row">ID</th>
                            <td>{{user.id}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Email</th>
                            <td>{{user.email}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Admin</th>
                            <td>{{user.admin}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4 d-none d-md-block"></div>
    </div>
</div>
<!-- Fin Contenido -->
{% endblock %}